### ISSUE TITLE
Open to Pull Requests

### ISSUE THREAD

**Issue by NeverNude** [alex-pirozhenko/sklearn-pmml#3]
We're using PMML at my company, and I was starting on a sklearn -> pmml implementation myself before coming on this project.  Do you mind if I start developing and submit PRs against this project?  Are you still actively developing this?

**Comment by alex-pirozhenko** [comment]
Hi Evan,
Feel free to submit pull requests! I plan to keep adding support for new
models and keep this library compatible with most commonly used PMML
processors, including JPMML and Knime.

**Comment by NeverNude** [comment]
OK awesome!  PR incoming soon
