### ISSUE TITLE
JPMML integration tests?

### ISSUE THREAD

**Issue by NeverNude** [alex-pirozhenko/sklearn-pmml#5]
How do you feel about adding JPMML integration tests to this?  I was thinking of adding a separate submodule project for a simple class that executes JPMML, writes the results to a file, so we can verify the sklearn predictions against the JPMML evaluator results.

**Comment by alex-pirozhenko** [comment]
That would be great. I perform these checks manually when I validate PMML serializations for FT, but it's definitely a good idea to automate them.
jpmml-evaluator-example already has a class that does exactly what we're looking for. See the example section of their [README](https://github.com/jpmml/jpmml-evaluator):

```
java -cp target/example-1.2-SNAPSHOT.jar org.jpmml.evaluator.EvaluationExample --model model.pmml --input input.tsv --output output.tsv
```

**Comment by NeverNude** [comment]
OK.  I'm going to use that, but with the 1.0.22 version of jpmml-evaluator, to avoid the AGPL licensing issues if people want to incorporate this into commercial projects.  Not sure if we can incorporate AGPL stuff for test purposes explicitly.

**Comment by NeverNude** [comment]
Merged with the latest set of changes
